name: flutter_async_value
description: A simple and elegant way to handle async states (initial, loading, data, error) in Flutter apps.
version: 1.3.0
repository: https://github.com/MajdHajHmidi/flutter_async_value.git
homepage: https://github.com/MajdHajHmidi/flutter_async_value

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
